name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Clone Theme
        uses: actions/checkout@v5
        with:
          repository: "alexandrevicenzi/Flex"
          ref: "v2.5.0"
          path: "Flex"
      - name: install theme
        run: pelican-themes --install Flex
      - name: Build Pelican site
        run: |
          pelican \
            --settings "publishconf.py" \
            --extra-settings SITEURL='"${{ steps.pages.outputs.base_url }}"' \
            --output "build" \
            --verbose
      - name: Fix permissions
        run: |
          chmod -c -R +rX "build" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4